QT += widgets

CONFIG += c++11

CONFIG += warn_off

LIBS+= -lglut -lGL -lGLU -lwordnet

INCLUDEPATH += -I../source

HEADERS         = NLCImain.hpp NLCImainWindow.hpp NLCIeditorWindow.hpp  NLCIeditorSyntaxHighlighter.hpp NLCIeditorOperations.hpp NLCItextDisplayWindow.hpp NLCItextDisplayWindow.hpp NLCIoperations.hpp \
../NLC/NLCmain.hpp ../NLC/NLCcodeBlockClass.hpp ../NLC/NLCclassDefinitionClass.hpp ../NLC/NLCitemClass.hpp ../NLC/NLCtranslator.hpp ../NLC/NLCtranslatorCodeBlocks.hpp ../NLC/NLCtranslatorCodeBlocksLogicalConditions.hpp ../NLC/NLCtranslatorCodeBlocksLogicalConditionsAdvanced.hpp ../NLC/NLCtranslatorCodeBlocksOperations.hpp ../NLC/NLCtranslatorClassDefinitions.hpp ../NLC/NLCprint.hpp ../NLC/NLCprintCodeBlocks.hpp ../NLC/NLCprintCodeBlocksFunctions.hpp ../NLC/NLCprintClassDefinitions.hpp ../NLC/NLCprintDefs.hpp ../NLC/NLCpreprocessor.hpp ../NLC/NLCpreprocessorSentenceClass.hpp ../NLC/NLCpreprocessorMath.hpp ../NLC/NLCpreprocessorMathLogicalConditions.hpp ../NLC/NLCapi.hpp ../NLC/GIAmain.hpp ../NLC/GIAnlpParser.hpp ../NLC/GIAtranslator.hpp ../NLC/GIAtranslatorDefineGrammar.hpp ../NLC/GIAtranslatorDefineReferencing.hpp ../NLC/GIAtranslatorRedistributeRelations.hpp ../NLC/GIAtranslatorRedistributeRelationsStanford.hpp ../NLC/GIAtranslatorRedistributeRelationsRelex.hpp ../NLC/GIAtranslatorLinkEntities.hpp ../NLC/GIAtranslatorLinkEntitiesDynamic.hpp ../NLC/GIAtranslatorApplyAdvancedFeatures.hpp ../NLC/GIAtranslatorOperations.hpp ../NLC/GIAentityNodeClass.hpp ../NLC/GIAentityConnectionClass.hpp ../NLC/GIAconditionNodeClass.hpp ../NLC/GIAsentenceClass.hpp ../NLC/GIAdraw.hpp ../NLC/GIAxmlConversion.hpp ../NLC/GIAcxlConversion.hpp ../NLC/GIAquery.hpp ../NLC/GIAdatabase.hpp ../NLC/GIAnlp.hpp ../NLC/GIAwordnet.hpp ../NLC/GIAnlg.hpp ../NLC/GIApreprocessor.hpp ../NLC/GIApreprocessorSentenceClass.hpp ../NLC/GIApreprocessorMultiwordReduction.hpp ../NLC/GIApreprocessorMultiwordReductionClass.hpp ../NLC/GIApreprocessorLogicReference.hpp ../NLC/GIApreprocessorReferenceSet.hpp ../NLC/GIAbot.hpp ../NLC/GIAtranslatorGeneric.hpp ../NLC/GIAtranslatorRules.hpp ../NLC/GIAsemanticParser.hpp ../NLC/GIAsemanticParserOperations.hpp ../NLC/GIAsemanticParserTranslator.hpp ../NLC/GIAsemanticParserDatabase.hpp ../NLC/XMLparserClass.hpp ../NLC/XMLrulesClass.hpp ../NLC/LDsvg.hpp ../NLC/LDopengl.hpp ../NLC/LDparser.hpp ../NLC/LDsprite.hpp ../NLC/LDreferenceManipulation.hpp ../NLC/LDreferenceClass.hpp ../NLC/RTpixelMaps.hpp ../NLC/RTppm.hpp ../NLC/RTviewinfo.hpp ../NLC/SHAREDglobalDefs.hpp ../NLC/SHAREDvector.hpp ../NLC/SHAREDvars.hpp \
../source/NLCglobalDefs.hpp ../source/GIAglobalDefs.hpp

SOURCES         = NLCImain.cpp NLCImainWindow.cpp NLCIeditorWindow.cpp  NLCIeditorSyntaxHighlighter.cpp NLCIeditorOperations.cpp NLCItextDisplayWindow.cpp NLCItextDisplayWindow.cpp NLCIoperations.cpp \
../NLC/NLCmain.cpp ../NLC/NLCcodeBlockClass.cpp ../NLC/NLCclassDefinitionClass.cpp ../NLC/NLCitemClass.cpp ../NLC/NLCtranslator.cpp ../NLC/NLCtranslatorCodeBlocks.cpp ../NLC/NLCtranslatorCodeBlocksLogicalConditions.cpp ../NLC/NLCtranslatorCodeBlocksLogicalConditionsAdvanced.cpp ../NLC/NLCtranslatorCodeBlocksOperations.cpp ../NLC/NLCtranslatorClassDefinitions.cpp ../NLC/NLCprint.cpp ../NLC/NLCprintCodeBlocks.cpp ../NLC/NLCprintCodeBlocksFunctions.cpp ../NLC/NLCprintClassDefinitions.cpp ../NLC/NLCprintDefs.cpp ../NLC/NLCpreprocessor.cpp ../NLC/NLCpreprocessorSentenceClass.cpp ../NLC/NLCpreprocessorMath.cpp ../NLC/NLCpreprocessorMathLogicalConditions.cpp ../NLC/NLCapi.cpp ../NLC/GIAmain.cpp ../NLC/GIAnlpParser.cpp ../NLC/GIAtranslator.cpp ../NLC/GIAtranslatorDefineGrammar.cpp ../NLC/GIAtranslatorDefineReferencing.cpp ../NLC/GIAtranslatorRedistributeRelations.cpp ../NLC/GIAtranslatorRedistributeRelationsStanford.cpp ../NLC/GIAtranslatorRedistributeRelationsRelex.cpp ../NLC/GIAtranslatorDefineSubstances.cpp ../NLC/GIAtranslatorLinkEntities.cpp ../NLC/GIAtranslatorLinkEntitiesDynamic.cpp ../NLC/GIAtranslatorApplyAdvancedFeatures.cpp ../NLC/GIAtranslatorOperations.cpp ../NLC/GIAentityNodeClass.cpp ../NLC/GIAentityConnectionClass.cpp ../NLC/GIAconditionNodeClass.cpp ../NLC/GIAsentenceClass.cpp ../NLC/GIAdraw.cpp ../NLC/GIAxmlConversion.cpp ../NLC/GIAcxlConversion.cpp ../NLC/GIAquery.cpp ../NLC/GIAdatabase.cpp ../NLC/GIAnlp.cpp ../NLC/GIAwordnet.cpp ../NLC/GIAnlg.cpp ../NLC/GIApreprocessor.cpp ../NLC/GIApreprocessorSentenceClass.cpp ../NLC/GIApreprocessorMultiwordReduction.cpp ../NLC/GIApreprocessorMultiwordReductionClass.cpp ../NLC/GIApreprocessorLogicReference.cpp ../NLC/GIApreprocessorReferenceSet.cpp ../NLC/GIAbot.cpp ../NLC/GIAtranslatorGeneric.cpp ../NLC/GIAtranslatorRules.cpp ../NLC/GIAsemanticParser.cpp ../NLC/GIAsemanticParserOperations.cpp ../NLC/GIAsemanticParserTranslator.cpp ../NLC/GIAsemanticParserDatabase.cpp ../NLC/XMLparserClass.cpp ../NLC/XMLrulesClass.cpp ../NLC/LDsvg.cpp ../NLC/LDopengl.cpp ../NLC/LDparser.cpp ../NLC/LDsprite.cpp ../NLC/LDreferenceManipulation.cpp ../NLC/LDreferenceClass.cpp ../NLC/RTpixelMaps.cpp ../NLC/RTppm.cpp ../NLC/RTviewinfo.cpp ../NLC/SHAREDglobalDefs.cpp ../NLC/SHAREDvector.cpp ../NLC/SHAREDvars.cpp

# install
target.path = /home/user/source/NLCI/NLCI/
INSTALLS += target
