#ifndef HEADER_NLC_GENERATED_functionsWithNoSubjectArtificialClass
#define HEADER_NLC_GENERATED_functionsWithNoSubjectArtificialClass

#include "NLClibraryGenericEntityClass.hpp"

class NLCimplicitlyDeclaredFunctionArtificialClass;
class functionsWithNoSubjectArtificialClass : public NLCgenericEntityClass
{
public:
	functionsWithNoSubjectArtificialClass(void);
	void NLCimplicitlyDeclaredFunctionArtificialFunction(vector<NLCimplicitlyDeclaredFunctionArtificialClass*>& NLCimplicitlyDeclaredFunctionArtificialClassList);
};

int main();
#endif
