 /*******************************************************************************
 *
 * License: GNU Affero General Public License version 3 (AGPLv3)
 *
 *******************************************************************************/

/*******************************************************************************
 *
 * File Name: NLClibraryStandardMove.hpp
 * Author: Richard Bruce Baxter - Copyright (c) 2005-2022 Baxter AI (baxterai.com)
 * Project: Natural Language Compiler (Programming Interface)
 * Project Version: 2p1a 05-June-2022
 * Requirements: requires C++ code to be generated by NLC
 *
 *******************************************************************************/
 
#ifndef HEADER_NLC_LIBRARY_STANDARD_MOVE
#define HEADER_NLC_LIBRARY_STANDARD_MOVE

#include "NLClibraryGenericEntityClass.hpp"

void moveFunction(vector<NLCgenericEntityClass*>& moveClassList, vector<NLCgenericEntityClass*>& moveObjectClassList);

#endif
