/*******************************************************************************
 *
 * This file is part of BAIPROJECT.
 *
 * BAIPROJECT is commercially licensed software. It may not be redistributed,
 * and may only be used by a registered licensee.
 *
 * BAIPROJECT is sold in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * BAI Commercial License for more details
 * (a copy is included in the LICENSE file that accompanied this code).
 *
 * You will have received a copy of the BAI Commercial License
 * along with BAIPROJECT. For more information, visit <http://www.baxterai.com>
 *
 *******************************************************************************/

/*******************************************************************************
 *
 * File Name: NLClibraryStandard.hpp
 * Author: Richard Bruce Baxter - Copyright (c) 2005-2016 Baxter AI (baxterai.com)
 * Project: Natural Language Compiler (Programming Interface)
 * Project Version: 1v13a 25-October-2016
 * Requirements: requires C++ code to be generated by NLC
 *
 *******************************************************************************/
 
#ifndef HEADER_NLC_LIBRARY_STANDARD
#define HEADER_NLC_LIBRARY_STANDARD

#include "NLClibraryGenericEntityClass.hpp"
#include "NLClibraryStandardCopy.hpp"
#include "NLClibraryStandardDelete.hpp"
#include "NLClibraryStandardFileIO.hpp"
#include "NLClibraryStandardMath.hpp"
#include "NLClibraryStandardMove.hpp"
#include "NLClibraryStandardPrint.hpp"
#include "NLClibraryStandardSet.hpp"

#endif
