 /*******************************************************************************
 *
 * License: GNU Affero General Public License version 3 (AGPLv3)
 *
 *******************************************************************************/

/*******************************************************************************
 *
 * File Name: NLClibraryStandardMath.hpp
 * Author: Richard Bruce Baxter - Copyright (c) 2005-2022 Baxter AI (baxterai.com)
 * Project: Natural Language Compiler (Programming Interface)
 * Project Version: 2p1a 05-June-2022
 * Requirements: requires C++ code to be generated by NLC
 *
 *******************************************************************************/
 
#ifndef HEADER_NLC_LIBRARY_STANDARD_MATH
#define HEADER_NLC_LIBRARY_STANDARD_MATH

#include "NLClibraryStandard.hpp"

#ifdef NLC_MATH_OBJECTS
bool isStringNumberOrFractional(string phrase);				//copied from NLCpreprocessorSentenceClass.cpp
bool isDecimalPlace(int indexOfCurrentToken, string* lineContents);	//copied from NLCpreprocessorSentenceClass.cpp
#endif

#endif
